### ISSUE TITLE
Token not automatically renewed / MyPeugeot credentials needed each day

### ISSUE THREAD

**Issue by CalicodesIles** [flobz/psa_car_controller#155] opened 2021-06-01 08:18 UTC
**Describe the bug**
Since 2 or 3 days ago, I must restart manually psa_car_controller because it seems that the token is not valid after a while, with a Python error : 

```
192.168.1.34 - - [01/Jun/2021 07:42:38] "GET /get_vehicleinfo/XXXXXXXXXXXXXX HTTP/1.1" 500 -
2021-06-01 07:42:38,908 :: INFO :: <Request 'http://192.168.1.35:5000/charge_control?vin=XXXXXXXXXXXXXX&%3Falways_check=true' [GET]>
192.168.1.34 - - [01/Jun/2021 07:42:38] "GET /charge_control?vin=XXXXXXXXXXXXXX&?always_check=true HTTP/1.1" 200 -
Exception on /get_vehicleinfo/XXXXXXXXXXXXXX [GET]
Traceback (most recent call last):
  File "/usr/local/src/psa_car_controller/libs/oauth.py", line 64, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api_client.py", line 351, in request
    headers=headers)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/rest.py", line 238, in GET
    query_params=query_params)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_connectedcar.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'WWW-Authenticate': 'Bearer error="invalid_token"', 'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Set-Cookie': 'PSACountry=FR;Domain=.groupe-psa.com;Path=/', 'Vary': 'Accept-Encoding'})
HTTP response body: { "httpCode":"401", "httpMessage":"Unauthorized", "moreInformation":"Token is not active" }


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/src/psa_car_controller/web/views.py", line 115, in get_vehicle_info
    response=json.dumps(myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/src/psa_car_controller/my_psacc.py", line 151, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1307, in get_vehicle_status_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/src/psa_car_controller/libs/oauth.py", line 75, in call_api
    self.configuration.refresh_callback()
  File "/usr/local/src/psa_car_controller/my_psacc.py", line 121, in refresh_token
    self.manager._refresh_token()
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/oauth2_client/credentials_manager.py", line 179, in _refresh_token
    raise err
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/oauth2_client/credentials_manager.py", line 173, in _refresh_token
    self._token_request(payload, False)
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/oauth2_client/credentials_manager.py", line 190, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/src/psa_car_controller/.env/lib/python3.7/site-packages/oauth2_client/credentials_manager.py", line 78, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - invalid_grant : grant is [invalid]
```

Then, when I restart psa_car_controller, I can't use the startup script as it asks me to re-enter my MyPeugeot credentials (login/password).

**To Reproduce**
1. what command did you use : **/usr/local/bin/psa_car_controller -f config.json -c charge_config.json -l 0.0.0.0 -r**
2. when the bug append ? **Each day. I didn't count how many hours precisely**
3. Does it persist after restarting the program? **Yes** 

**Config file**
```
$ cat config.json 
{
    "abrp": {
        "abrp_enable_vin": [
            "XXXXXXXXXXXXXXXXX"
        ],
        "token": "XXXXXXXXXXXXXXXXX"
    },
    "client_id": "XXXXXXXXXXXXXXXXX",
    "client_secret": "XXXXXXXXXXXXXXXXX",
    "co2_signal_api": null,
    "country_code": "FR",
    "customer_id": "AP-ACNTXXXXXXXXXX",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "XXXXXXXXXXXXXXXXX",
    "remote_refresh_token": "XXXXXXXXXXXXXXXXX",
    "weather_api": "XXXXXXXXXXXXXXXXX"
```

**Environment (please complete the following information):**
 - OS: **Linux Debian 10.9**
 - Android app: **Version APK 1.28.1**
 - Brand and model of car: **Peugeot e208**
 - Application version (commit number, branch): **Latest commit** 

**Additional context**
It was working correctly since a few weeks. It happened recently.
I already tried to delete otp.bin and regenerate elements through the whole process with "python3 app_decoder.py /home/psa_remote/com.psa.mym.mypeugeot_1.28.1.apk"

If I'm not wrong, I noticed some messages with process_code and process_message that I didn't see before, maybe it is related with some Peugeot actions in their API :

`
Jun 01 10:00:27 PSA1 psa_car_controller[1071]: 2021-06-01 10:00:27,663 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACNTXXXXXXXXXXX/VehicleState b'{"resp_date":"2021-06-01T08:00:28Z","vin":"XXXXXXXXXXXXXXXX","correlation_id":"15ac6fc8dfdf4877b0b08a8d852dcb7c20210601080026948","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}' 
`

Then after wakeup of the vehicle

```
Jun 01 10:02:28 PSA1 psa_car_controller[1071]: 2021-06-01 10:02:28,601 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACNTXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2021-06-01T08:02:29Z","vin":"XXXXXXXXXXXXXXXX","correlation_id":"7d4c6b20cf08432192623a4d8c8b94a520210601080227950","process_code":"900","process_message":"[process.900.request.accepted.key]"}'

Jun 01 10:02:28 PSA1 psa_car_controller[1071]: 2021-06-01 10:02:28,790 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACNTXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2021-06-01T08:02:29Z","vin":"XXXXXXXXXXXXXXXX","correlation_id":"7d4c6b20cf08432192623a4d8c8b94a520210601080227950","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'

Jun 01 10:02:49 PSA1 psa_car_controller[1071]: 2021-06-01 10:02:49,090 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACNTXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2021-06-01T08:02:49Z","vin":"XXXXXXXXXXXXXXXX","correlation_id":"7d4c6b20cf08432192623a4d8c8b94a520210601080227950","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
```

**Comment by aleblack** [comment] 2021-06-01 10:43
I'm having the exact same problem since saturday.

**Comment by dreimer1986** [comment] 2021-06-03 23:58
Same here. PSA having fun again?

**Comment by CalicodesIles** [comment] 2021-06-04 15:00
FYI No issue with token regeneration since 2 days

**Comment by flobz** [comment] 2021-06-04 15:45
It can be related to change in MQTT API. 
Can you retry with latest version : c946a2f

**Comment by CalicodesIles** [comment] 2021-06-06 20:12
Seems OK for the moment, I didn't have to restart psa_car_controller yet. Thank you @flobz 

For the others, is it slightly better than before with his latest version ?

**Comment by aleblack** [comment] 2021-06-06 20:44
Looks like the problem is fixed now. Thanks.

**Comment by dreimer1986** [comment] 2021-06-07 07:37
Looks fine since a few days here too. (Updated to newest master build)

**Comment by flobz** [comment] 2021-06-07 11:50
thanks for your feedback.

**Closed by flobz** 2021-06-07 11:50 UTC
