### ISSUE TITLE
Error with charge_control

### ISSUE THREAD

**Issue by Flodu31** [flobz/psa_car_controller#61] opened 2021-04-02 15:06 UTC
**Describe the bug**
When calling the charge_control api, I've the following error:

```
2021-04-02 17:02:37,525 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=vin&%3Falways_check=true' [GET]>
2021-04-02 17:03:29,377 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/src/psa_car_controller/ChargeControl.py", line 57, in start
    status = res.energy[0].charging.status
AttributeError: 'NoneType' object has no attribute 'status'
```

**To Reproduce**
1. what command did you use
http://localhost:5000/charge_control?vin=vin
2. when the bug append ?
From last week
3. Does it persist after restarting the program? 
4. Yes

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: Pi
 - Android app Version: 28.0
 - Brand and model of car: e2008
 - Application version (commit number, branch): master

**Additional context**
I know that for the getvehicle, it changed from 0 to 1 and I don't know why.

**Comment by flobz** [comment] 2021-04-03 08:15
You don't have the last version. It should be fixed now. 
It's caused by psa api, the prod server seems to be the dev one also...

**Comment by Flodu31** [comment] 2021-04-03 11:31
I tried to use the last version, but I have the following error:

```
Can't get car model please check cars.json
Traceback (most recent call last):
  File "app_decoder.py", line 151, in <module>
    label = vehicle["short_label"].split(" ")[-1]
KeyError: 'short_label'
```
Thanks

**Comment by Flodu31** [comment] 2021-04-03 12:05
```
2021-04-03 14:04:23,445 :: ERROR :: update_trips: Traceback (most recent call last):
  File "/usr/local/src/psa_car_controller/web/views.py", line 142, in update_trips
    trips = next(iter(trips_by_vin.values()))  # todo handle multiple car
StopIteration

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/src/psa_car_controller/web/app.py", line 42, in start_app
    import web.views
  File "/usr/local/src/psa_car_controller/web/views.py", line 204, in <module>
    update_trips()
  File "/usr/local/src/psa_car_controller/web/views.py", line 149, in update_trips
    min_date = trips[0].start_at
NameError: name 'trips' is not defined
```

**Comment by dreimer1986** [comment] 2021-04-03 14:35
I almost thought I was alone with that one again ^^ https://github.com/flobz/psa_car_controller/issues/53 Thanks for verification :D

**Comment by flobz** [comment] 2021-04-06 08:57
Ok last error should be fixed now.


> I tried to use the last version, but I have the following error:
> 
> ```
> Can't get car model please check cars.json
> Traceback (most recent call last):
>   File "app_decoder.py", line 151, in <module>
>     label = vehicle["short_label"].split(" ")[-1]
> KeyError: 'short_label'
> ```
> 
> Thanks

Can you retry with last version, It should print the api response.  Can you check if in that response you see your model ?

**Comment by Flodu31** [comment] 2021-04-06 10:52
Hello,

it works fine now, I can see this before the Success message:

'label': None, 'brand': 'Peugeot', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]

thanks for your help
florent

**Comment by Flodu31** [comment] 2021-04-06 10:53
I also always have empty values

Apr 06 12:51:44 FLOAPP-PEUGEOT psa_car_controller[4678]: 2021-04-06 12:51:44,398 :: ERROR :: kinetic not available from api
Apr 06 12:51:44 FLOAPP-PEUGEOT psa_car_controller[4678]: 2021-04-06 12:51:44,399 :: ERROR :: last_position not available from api

**Comment by flobz** [comment] 2021-04-06 11:33
> Hello,
> 
> it works fine now, I can see this before the Success message:
> 
> 'label': None, 'brand': 'Peugeot', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
> 
> thanks for your help
> florent

Can you give me the output before that ?

**Comment by Flodu31** [comment] 2021-04-06 13:28
Here is the full log:

```
Can't get car model please check cars.json
{'vin': 'VIN', 'lcdv': 'Numberandletters', 'warranty_start_date': DATE, 'visual': 'https://visuel3d-secure.peugeot.com/V3DImage.ashx?client=MyMarque&format=png&back=0&view=001&version=1PP1SYZESFB0A0C0&color=0MM60NSM&trim=0P2A0RFX&OPT1=E301&OPT2=LW02&OPT3=LZ04&OPT4=TC07&OPT5=WY45&width=1080', 'eligibility': ['device_nac', 'cea', 'update_software_nac', 'update_carto_nac', 'tmts', 'remotelev', 'navcozar'], 'attributes': ['DCD00CD', 'DCX01CD', 'DRCNNCD', 'DRE07CD', 'DXD04CD'], 'type_vehicle': 4, 'external_ws_status': 'OK', 'mileage': {'value': 0, 'source': 1, 'timestamp': 0}}

Your vehicles: ["{'vin': 'VIN', 'vehicle_id': 'letterandnumber', 'label': None, 'brand': 'Peugeot', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
Success !!!
```
Florent

**Comment by flobz** [comment] 2021-04-06 13:55
Ok thanks.
API doesn't give you the model...

**Closed** 2021-04-08 17:47 UTC
