### ISSUE TITLE
Issue with pre-conditionning

### ISSUE THREAD

**Issue by zoic21** [flobz/psa_car_controller#581] opened 2023-07-10 13:51 UTC
**Describe the bug**

Preconditionning don't work anymore

**To Reproduce**

Ask to preconditionning on

**Config file**

```
[General]
currency = €
# minimum trip length in km so it's added to stats and map in website
minimum trip length = 10
# for future use
length unit = km
[Electricity config]
# price by kw/h
day price = 0.15
night price
# ex: 22h30
night hour start
# ex: 6h00
night hour end
dc charge price
high speed dc charge price
# minimum power in kW that should be delivered during a charge so it can be considered as a high speed charger
high speed dc charge threshold
charger efficiency = 0.8942
```

**Environment (please complete the following information):**
 - OS: Docker
 - Peugot 3008
 - Application version : latest tag from docker (update to date as now)

```
2023-07-10 13:42:49,470 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 38, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
```
```
2023-07-10 13:48:08,252 :: INFO :: Preconditioning: topic: psa/RemoteServices/from/cid/AP-XXXXXXX/ThermalPrecond: {'asap': 'activate', 'programs': {'program1': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program2': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program3': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program4': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}}}
2023-07-10 13:48:25,483 :: INFO :: save config change
```

**Comment by pierrecelle38** [comment] 2023-07-18 07:50
I have exactly the same issue.
docker
last tag version
peugeot e2008

PSACC_OPTIONS="-c -r --web-conf"

Thanks,

Pierre

**Comment by flobz** [comment] 2023-10-29 16:14
Duplicate of #552

**Closed by flobz** 2023-10-29 16:14 UTC
Labels: bug
