### ISSUE TITLE
User Config error : {"code":"495", "message": "Invalid or expired client certificate"}

### ISSUE THREAD

**Issue by MenzeJan** [flobz/psa_car_controller#618] opened 2023-09-21 07:24 UTC
**Bug**
When i want to login in the My Car Info tab i get the following error:

Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 78, in firstLaunchConfig res_dict = res2.json()["success"] KeyError: 'success' {"code":"495", "message": "Invalid or expired client certificate"}

![image](https://github.com/flobz/psa_car_controller/assets/144695818/263d9d55-8201-4413-9dce-206a2079e560)

**Comment by flobz** [comment] 2023-09-22 14:34
Duplicate of #617

**Closed by flobz** 2023-09-22 14:34 UTC
